name: JS Code Convention

on:
  push:
    branches:
      - main
      - laboratory-work-4

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Biome
        run: npm install --save-dev --save-exact @biomejs/biome

      - name: Lint ProgramCode.js
        run: npx biome check ./2.6-GitHubActions/ProgramCode.js

      - name: Lint ProgramCodeModified.js (ignore fail)
        run: npx biome check ./2.6-GitHubActions/ProgramCodeModified.js || true
